Rename and Fix
Signed-off-by: Koichi Shiraishi <k@zchee.io>

diff --git a/bin/build-llvm b/bin/build-llvm
--- a/bin/build-llvm
+++ b/bin/build-llvm
@@ -9,7 +9,7 @@ set -e
 #   - ninja
 #
 # Usage:
-#   build-llvm.bash <LLVM Source Directory> <CMAKE GENERATORS> <PYTHON VERSION> [$SOURCE_DIR $DIST_DIR]
+#   build-llvm.bash <LLVM SOURCES ROOT> <CMAKE GENERATORS> <PYTHON VERSION> [DIST_DIR]
 #
 #   CMake Generators: Unix Makefiles, Ninja, Xcode (Recommend is Ninja)
 #
@@ -31,92 +31,77 @@ set -e
 #     - When LLVM_ENABLE_LTO, link for llvm-dsymutil too slow...
 #     - github.com/apple/apple-llvm instead of
 #     - -DLLVM_TOOL_DSYMUTIL_BUILD:BOOL=OFF
-#   - clang: error: unsupported argument 'all' to option 'fno-sanitize='
-#     - ag "  -fno-sanitize=all" -l | xargs sed -i 's/  -fno-sanitize=all//'
-#     - Maybe -DLLVM_USE_SANITIZER:STRING=Undefined ?
-#
 
 
-if ! [[ -n $1 ]]; then
-  echo "llvm source directory"
-  exit 1
-fi
-if ! [[ $DST_DIR ]]; then
+# define install directory
+if [[ $4 ]]; then
+  DST_DIR=$4
+else
   DST_DIR=/opt/llvm
 fi
 
-PYTHON_SELECT_VERSION=$(python$3-config --prefix | awk -F / '{print $NF}')
+# define Python Frameworks path
+PYTHON_PREFIX=$(python"$3"-config --prefix)
+PYTHON_SELECT_VERSION=$(python"$3"-config --prefix | awk -F / '{print $NF}')
 
-if ! [[ -n $PYTHON_PREFIX ]]; then
-  PYTHON_PREFIX=$(python$3-config --prefix)
+PYTHON_EXECUTABLE=$(which python"$3")
+PYTHON_INCLUDE_DIR=$PYTHON_PREFIX/include/python$PYTHON_SELECT_VERSION
+if [[ $3 == 3 ]]; then
+  PYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR$(python$3-config --abiflags)
 fi
-
-# -DPYTHON_EXECUTABLE=/usr/local/bin/python3
-if ! [[ -n $PYTHON_EXECUTABLE ]]; then
-  PYTHON_EXECUTABLE=$(which python$PYTHON_SELECT_VERSION)
-fi
-# -DPYTHON_INCLUDE_DIR=/usr/local/Frameworks/Python.framework/Versions/3.6/include/python3.6m
-if ! [[ -n $PYTHON_INCLUDE_DIR ]]; then
-  if ! [[ -n $3 == "3" ]]; then
-    PYTHON_INCLUDE_DIR=$PYTHON_PREFIX/include/python$PYTHON_SELECT_VERSIONm
-  else
-    PYTHON_INCLUDE_DIR=$PYTHON_PREFIX/include/python$PYTHON_SELECT_VERSION
-  fi
-fi
-# -DPYTHON_LIBRARY=/usr/local/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib
-if ! [[ -n $PYTHON_LIBRARY ]]; then
-  PYTHON_LIBRARY=$PYTHON_PREFIX/lib/libpython$PYTHON_SELECT_VERSION.dylib
-fi
+PYTHON_LIBRARY=$PYTHON_PREFIX/lib/libpython$PYTHON_SELECT_VERSION.dylib
 
 
-
-USAGE_CMAKE_GENERATORS="\
-  Unix Makefiles
-  Ninja
-  Xcode
-  CodeBlocks - Ninja
-  CodeBlocks - Unix Makefiles
-  CodeLite - Ninja
-  CodeLite - Unix Makefiles
-  Eclipse CDT4 - Ninja
-  Eclipse CDT4 - Unix Makefiles
-  KDevelop3
-  KDevelop3 - Unix Makefiles
-  Kate - Ninja
-  Kate - Unix Makefiles
-  Sublime Text 2 - Ninja
-  Sublime Text 2 - Unix Makefiles"
-USAGE_PYTHON_VERSION="\
-  2
-  3"
-USAGE_ENVIRONMENT_VARIABLE="\
-  \$SRC_DIR		$SRC_DIR
-  \$DST_DIR		$DST_DIR
-  \$PYTHON_EXECUTABLE	$PYTHON_EXECUTABLE
-  \$PYTHON_INCLUDE_DIR	$PYTHON_INCLUDE_DIR
-  \$PYTHON_LIBRARY	$PYTHON_LIBRARY"
+# Usage
 usage() {
+  USAGE_CMAKE_GENERATORS="\
+Unix Makefiles
+    Ninja
+    Xcode
+    CodeBlocks - Ninja
+    CodeBlocks - Unix Makefiles
+    CodeLite - Ninja
+    CodeLite - Unix Makefiles
+    Eclipse CDT4 - Ninja
+    Eclipse CDT4 - Unix Makefiles
+    KDevelop3
+    KDevelop3 - Unix Makefiles
+    Kate - Ninja
+    Kate - Unix Makefiles
+    Sublime Text 2 - Ninja
+    Sublime Text 2 - Unix Makefiles"
+  USAGE_PYTHON_VERSION="\
+2
+    3"
+  USAGE_ENVIRONMENT_VARIABLE="\
+\$SRC_DIR		$SRC_DIR
+    \$DST_DIR		$DST_DIR
+    \$PYTHON_EXECUTABLE	$PYTHON_EXECUTABLE
+    \$PYTHON_INCLUDE_DIR	$PYTHON_INCLUDE_DIR
+    \$PYTHON_LIBRARY	$PYTHON_LIBRARY"
+
   echo "error: No build tool as arguments"
   echo ""
-  echo "$0 <CMAKE GENERATORS> <PYTHON VERSION> [\$SOURCE_DIR \$DIST_DIR]"
+  echo "Usage: $0 <LLVM SOURCES ROOT> <CMake Generators> <Python Version> [\$DIST_DIR]"
   echo ""
   echo "CMake Generators"
-  echo "$USAGE_CMAKE_GENERATORS"
+  echo "    $USAGE_CMAKE_GENERATORS"
   echo ""
   echo "Python Version"
-  echo "$USAGE_PYTHON_VERSION"
+  echo "    $USAGE_PYTHON_VERSION"
   echo ""
   echo "Environment variable:"
-  echo "$USAGE_ENVIRONMENT_VARIABLE"
+  echo "    $USAGE_ENVIRONMENT_VARIABLE"
   exit 1
 }
+
+# Check len(args)
 if [[ ! -n $3 ]]; then
-  PYTHON_VERSION=3
   usage
 fi
 
 
-
+# define dependencies packages
 PYTHON="\
   -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE \
   -DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR \
@@ -130,42 +115,37 @@ LIBFFI="\
   -DFFI_LIBRARY_DIR=/usr/local/opt/libffi/lib/libffi.dylib"
 
 
-if [[ ! -d "$DST_DIR" ]]; then
-  mkdir -p $DST_DIR
+# Warning for have not '*build*' in current dir name
+if ! [[ $(readlink -f .) == *build* ]]; then
+  echo "Current dir needs build* name"
+  exit 1
 fi
-cd $DST_DIR
 
-command cmake $2 -G $1 \
+# if hash ccache 2>/dev/null; then
+#   export CC="ccache $CC"
+#   export CXX="ccache $CXX"
+# fi
+
+command cmake $1 -G $2 \
   \
   -DBUILD_SHARED_LIBS:BOOL=OFF \
-  \
-  -DCLANG_BUILD_EXAMPLES:BOOL=ON \
-  -DCLANG_DEFAULT_CXX_STDLIB:STRING=libc++ \
-  -DCLANG_INCLUDE_DOCS:BOOL=ON \
-  -DCLANG_INCLUDE_TESTS:BOOL=ON \
   \
   -DCMAKE_ASM_FLAGS:STRING='-march=native' \
   -DCMAKE_BUILD_TYPE:STRING=Release \
   -DCMAKE_CXX_FLAGS:STRING='-march=native' \
   -DCMAKE_C_FLAGS:STRING='-march=native' \
-  \
   -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON \
   -DCMAKE_FIND_FRAMEWORK=LAST \
   -DCMAKE_INSTALL_PREFIX:PATH=$DST_DIR \
-  \
   -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64 \
   -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.11 \
   -DCMAKE_OSX_SYSROOT:STRING="$(xcrun --show-sdk-path)" \
-  \
   -DCMAKE_SKIP_INSTALL_RPATH:BOOL=NO \
   -DCMAKE_SKIP_RPATH:BOOL=NO \
   \
-  -DCOMPILER_RT_DEBUG:BOOL=OFF \
-  -DCOMPILER_RT_ENABLE_IOS:BOOL=OFF \
-  -DCOMPILER_RT_ENABLE_TVOS:BOOL=OFF \
-  -DCOMPILER_RT_ENABLE_WATCHOS:BOOL=OFF \
-  -DCOMPILER_RT_ENABLE_WERROR:BOOL=OFF \
-  -DCOMPILER_RT_EXTERNALIZE_DEBUGINFO:BOOL=OFF \
+  -DCLANG_DEFAULT_CXX_STDLIB:STRING=libc++ \
+  -DCLANG_INCLUDE_DOCS:BOOL=ON \
+  -DCLANG_INCLUDE_TESTS:BOOL=ON \
   \
   -DCURSES_CURSES_LIBRARY:FILEPATH=/usr/local/lib/libcurses.dylib \
   -DCURSES_FORM_LIBRARY:FILEPATH=/usr/local/lib/libform.dylib \
@@ -173,14 +153,13 @@ command cmake $2 -G $1 \
   -DCURSES_NCURSES_LIBRARY:FILEPATH=/usr/local/lib/libncurses.dylib \
   -DCURSES_PANEL_LIBRARY:FILEPATH=/usr/local/lib/libpanel.dylib \
   \
-  -DDEFAULT_SYSROOT:PATH="$(xcrun --show-sdk-path)" \
-  \
-  -DLIBCLANG_BUILD_STATIC:BOOL=OFF \
+  -DLIBCLANG_BUILD_STATIC:BOOL=ON \
+  -DLIBCXX_ABI_UNSTABLE:BOOL=ON \
+  -DLIBCXX_CONFIGURE_IDE:BOOL=ON \
   -DLIBCXXABI_ENABLE_ASSERTIONS:BOOL=OFF \
   -DLIBCXXABI_SYSROOT:STRING="$(xcrun --show-sdk-path)" \
   -DLIBCXXABI_USE_LLVM_UNWINDER:BOOL=OFF \
   \
-  -DLIBCXX_CONFIGURE_IDE:BOOL=OFF \
   -DLIBCXX_ENABLE_ASSERTIONS:BOOL=OFF \
   -DLIBCXX_OVERRIDE_DARWIN_INSTALL:BOOL=ON \
   -DLIBCXX_SYSROOT:STRING="$(xcrun --show-sdk-path)" \
@@ -190,44 +169,50 @@ command cmake $2 -G $1 \
   \
   -DLLDB_EXPORT_ALL_SYMBOLS:BOOL=ON \
   \
-  -DLLD_USE_VTUNE:BOOL=OFF \
-  \
-  -DLLVM_BUILD_EXAMPLES:BOOL=ON \
   -DLLVM_BUILD_EXTERNAL_COMPILER_RT:BOOL=ON \
+  -DLLVM_BUILD_GLOBAL_ISEL:BOOL=ON \
   -DLLVM_BUILD_LLVM_C_DYLIB:BOOL=ON \
   -DLLVM_BUILD_LLVM_DYLIB:BOOL=ON \
   -DLLVM_CREATE_XCODE_TOOLCHAIN:BOOL=OFF \
   -DLLVM_ENABLE_ASSERTIONS:BOOL=OFF \
   -DLLVM_ENABLE_CXX1Y:BOOL=ON \
-  -DLLVM_ENABLE_FFI:BOOL=ON \
+  -DLLVM_ENABLE_FFI:BOOL=OFF \
   -DLLVM_ENABLE_LIBCXX:BOOL=ON \
   -DLLVM_ENABLE_LIBCXXABI:BOOL=ON \
-  -DLLVM_ENABLE_LTO:STRING=OFF \
   -DLLVM_ENABLE_SPHINX:BOOL=OFF \
-  -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD:STRING= \
-  -DLLVM_EXTERNALIZE_DEBUGINFO:BOOL=ON \
+  -DLLVM_EXTERNALIZE_DEBUGINFO:BOOL=OFF \
   -DLLVM_INCLUDE_DOCS:BOOL=ON \
-  -DLLVM_INCLUDE_EXAMPLES:BOOL=ON \
   -DLLVM_LINK_LLVM_DYLIB:BOOL=OFF \
   -DLLVM_OPTIMIZED_TABLEGEN:BOOL=ON \
   -DLLVM_PARALLEL_COMPILE_JOBS:STRING=8 \
   -DLLVM_PARALLEL_LINK_JOBS:STRING=8 \
   -DLLVM_TARGET_ARCH:STRING=host \
   -DLLVM_TARGETS_TO_BUILD:STRING=X86 \
-  -DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD:BOOL=OFF \
-  -DLLVM_TOOL_DSYMUTIL_BUILD:BOOL=OFF \
+  -DLLVM_TOOL_DSYMUTIL_BUILD:BOOL=ON \
   -DLLVM_USE_SPLIT_DWARF:BOOL=OFF \
   \
   -DPOLLY_ENABLE_GPGPU_CODEGEN:BOOL=ON \
   \
-  \
   -Wno-dev \
   \
   $(echo $PYTHON) \
-  $(echo $LIBFFI) \
   $(echo $LIBXML2) \
   \
+  -DLLVM_ENABLE_LTO:STRING=OFF \
   -DLLVM_TOOL_LTO_BUILD:BOOL=OFF
+  # -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD:STRING= \
+  # $(echo $LIBFFI) \
+  # \
+  # -DC_INCLUDE_DIRS:STRING="$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/include:/usr/include" \
 
-  # -DDARWIN_10.4_ARCHS:STRING=x86_64 \
-  # -DDARWIN_osx_ARCHS:STRING=x86_64 \
+
+# Disable sanitizer (workaround)
+#   - clang: error: unsupported argument 'all' to option 'fno-sanitize='
+if hash ag 2>/dev/null; then
+  ag -l "  -fno-sanitize=all" | xargs sed -i 's/  -fno-sanitize=all//'
+elif hash grep 2>/dev/null; then
+  grep -l "  -fno-sanitize=all" $PWD | xargs sed -i 's/  -fno-sanitize=all//'
+else
+  echo "Disable sanitizer required "
+  exit 1
+fi
